### ISSUE TITLE
Chapter 08: error running the psystock_docker_training_image 

### ISSUE THREAD

**Issue by sqliam** [PacktPublishing/Machine-Learning-Engineering-with-MLflow#2]
Repro steps:
(1) Start the workbench in gradflow folder
(2) Follow the steps in Chapter 08 to build psystock_docker_training_image 
(3) Try to start it using the command in the book. 
Expected: it should start
Actual: it throws **UnsupportedModelRegistryStoreURIException**
`
mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 'file:///src/mlruns' for model registry data storage. Supported URI schemes are: ['databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/client.py", line 95, in _get_registry_client
    registry_client = ModelRegistryClient(self._registry_uri)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/_model_registry/client.py", line 36, in __init__
    self.store  # pylint: disable=pointless-statement
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/_model_registry/client.py", line 40, in store
    return utils._get_store(self.registry_uri)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/_model_registry/utils.py", line 169, in _get_store
    return _get_store_registry().get_store(store_uri)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/_model_registry/registry.py", line 37, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/_model_registry/registry.py", line 46, in _get_store_with_resolved_uri
    builder = self.get_store_builder(resolved_store_uri)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/registry.py", line 78, in get_store_builder
    raise UnsupportedModelRegistryStoreURIException(
mlflow.tracking.registry.UnsupportedModelRegistryStoreURIException:  Model registry functionality is unavailable; got unsupported URI 'file:///src/mlruns' for model registry data storage. Supported URI schemes are: ['databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql']. See https://www.mlflow.org/docs/latest/tracking.html#storage for how to run an MLflow server against one of the supported backend storage locations.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    workflow()
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "main.py", line 24, in workflow
    mlflow.register_model(
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/_model_registry/fluent.py", line 67, in register_model
    raise e
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/_model_registry/fluent.py", line 58, in register_model
    create_model_response = client.create_registered_model(name)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1642, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "/opt/conda/envs/mlflow-2419ee4e40c137a8bc2c11d494002db24746963f/lib/python3.8/site-packages/mlflow/tracking/client.py", line 102, in _get_registry_client
    raise MlflowException(
mlflow.exceptions.MlflowException: Model Registry features are not supported by the store with URI: 'file:///src/mlruns'. Stores with the following URI schemes are supported: ['databricks', 'http', 'https', 'postgresql', 'mysql', 'sqlite', 'mssql'].
2021/09/25 05:07:10 ERROR mlflow.cli: === Run (ID '02f7bd7a19264bddac29a1666e1f43a8') failed ===

**Comment by nlauchande** [comment]
@sqliam: Thank you very much for reporting this.  

At first glance:
1. This basically means that the instance of MLflow that the job is pointing to is not the one backed by the Development Environment that contains MLflow.

2. Need to test and reproduce on my side to see the best way to address this issue.

**Comment by hdotking** [comment]
I get the same error message on WSL2 when:

- running  `mlflow run .` in the /Chapter08/psystock-training/ directory 
- OR  running `docker run -e MLflow_TRACKING_SERVER=$TRACKING_SERVER_URI psystock_docker_training_image` in the /Chapter08/psystock-training-docker/

PS: If anyone is getting errors on the 2nd line of the Dockerfile (in the /Chapter08/psystock-training-docker/ directory) when building the image, try changing the line to the following:

`RUN apt-get --allow-releaseinfo-change update && apt-get install build-essential -y`

**Comment by webmakaka** [comment]
@nlauchande Hi!
I have the same issues. Can you fix it? 

And for what here file mlflow_db? 

 [mlflow_db](https://github.com/PacktPublishing/Machine-Learning-Engineering-with-MLflow/blob/master/Chapter08/psystock-training/mlflow_db)

For what here gradflow folder
[gradflow](https://github.com/PacktPublishing/Machine-Learning-Engineering-with-MLflow/tree/master/Chapter08/gradflow).

I didn't find anything about it in the book.

Thanks!

**Comment by webmakaka** [comment]
**My solution is:**

updated codes in my [repo](https://github.com/webmakaka/Machine-Learning-Engineering-with-MLflow)

<br/>

```
$ pip install mlflow
$ cd ~/tmp/Machine-Learning-Engineering-with-MLflow/Chapter09/gradflow/
$ export MLFLOW_TRACKING_URI=http://localhost:5000
$ mlflow db upgrade sqlite:///mlflow_db
$ make gradflow-light
```


<br/>

```
$ cd ~/tmp/Machine-Learning-Engineering-with-MLflow/Chapter08/psystock-training
```

<br/>

```
$ export MLFLOW_TRACKING_URI=http://localhost:5000
```

<br/>

```
$ mlflow run .
```


<br/>

```
localhost:5000
```

<br/>

But there is no artefacts.

**Comment by nlauchande** [comment]
Closing this as issue sound sorted. Will consider this in a future edition of the book .
