### ISSUE TITLE
Chapter 09 - `make gradflow-light` fails

### ISSUE THREAD

**Issue by hdotking** [PacktPublishing/Machine-Learning-Engineering-with-MLflow#9]
## Issue
`$ make gradflow-light` fails with:

```
make: *** No rule to make target 'gradflow-light'.  Stop.
```

## Inputs to reproduce

Page 157 says to navigate to Chapter09/gradflow/ directory and run the following 3 commands:

```
$ cd gradflow
$ export MLFLOW_TRACKING_URI=http://localhost:5000
$ make gradflow
```

The final command fails

## Observations

The Makefile  has no mention of `gradflow-light` and instead mentions `gradflow-tracking`

```
$ cat Makefile

gradflow-tracking:
        mlflow server --backend-store-uri sqlite:///mlflow_db  --default-artifact-root ./tmp/
```
Unfortunately, running `$ make gradflow-tracking` leads to further errors - displayed below:

```
$ make gradflow-tracking
mlflow server --backend-store-uri sqlite:///mlflow_db  --default-artifact-root ./tmp/
2021/11/11 18:35:11 ERROR mlflow.cli: Error initializing backend store
2021/11/11 18:35:11 ERROR mlflow.cli: Detected out-of-date database schema (found version 39d1c3be5f05, but expected c48cb773bb87). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
Traceback (most recent call last):
  File "/home/hdot/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/cli.py", line 383, in server
    initialize_backend_stores(backend_store_uri, default_artifact_root)
  File "/home/hdot/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/server/handlers.py", line 145, in initialize_backend_stores
    _get_tracking_store(backend_store_uri, default_artifact_root)
  File "/home/hdot/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/server/handlers.py", line 130, in _get_tracking_store
    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)
  File "/home/hdot/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/home/hdot/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/home/hdot/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/server/handlers.py", line 101, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/home/hdot/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 140, in __init__
    mlflow.store.db.utils._verify_schema(self.engine)
  File "/home/hdot/miniconda3/envs/mlflow_env/lib/python3.7/site-packages/mlflow/store/db/utils.py", line 58, in _verify_schema
    "more detail." % (current_rev, head_revision)
mlflow.exceptions.MlflowException: Detected out-of-date database schema (found version 39d1c3be5f05, but expected c48cb773bb87). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: sc
```

**Comment by ZoheeDH** [comment]
I was having the same problem, but found that the makefile in Chapter09/ makes mention of `gradflow-light`, then to fix the error `ERROR mlflow.cli: Detected out-of-date database schema` I ran the command `$ mlflow db upgrade sqlite:///mlflow_db`

**Comment by webmakaka** [comment]
```
$ pip install mlflow
$ cd ~/tmp/Machine-Learning-Engineering-with-MLflow/Chapter09/gradflow/
$ export MLFLOW_TRACKING_URI=http://localhost:5000
$ mlflow db upgrade sqlite:///mlflow_db
$ make gradflow-tracking
```


<br/>

Also i think that need to add --host 0.0.0.0 in Makefile

```
gradflow-tracking:
        mlflow server --backend-store-uri sqlite:///mlflow_db  --default-artifact-root ./tmp/ --host 0.0.0.0
```

**Comment by webmakaka** [comment]
upd

Makefile with gradflow-light (if needed) 

https://github.com/PacktPublishing/Machine-Learning-Engineering-with-MLflow/blob/master/Chapter09/Makefile

**Comment by nlauchande** [comment]
Merging @webmakaka fixes that on this pull request : https://github.com/PacktPublishing/Machine-Learning-Engineering-with-MLflow/pulls . Need to go by myself on it.
